### ISSUE TITLE
why to adding other payment method

### ISSUE THREAD

**Issue by frand-kod** [naufkia/mikpos#2]
Here I am… Hi! I successfully installed MikPos and integrated it with Tripay payment. In my case, I can't find other e-wallet payment methods like Dana or OVO, and by default, MikPos does not support them.

So, what can I do to add these outside MikPos default settings, sir?

**Comment by nauxxyzn** [comment]
> Here I am… Hi! I successfully installed MikPos and integrated it with Tripay payment. In my case, I can't find other e-wallet payment methods like Dana or OVO, and by default, MikPos does not support them.
> 
> So, what can I do to add these outside MikPos default settings, sir?

bisa saja, silahkan buat code sendiri aja ya, karena ini opensource, udah ga saya maintain lagi, karena blm ada waktu🙏
